version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - mapk0y
  assignees:
  - mapk0y
  labels:
  - dependencies
